### ISSUE TITLE
This expression has type `Core.Std.bytes` but an expression was expected of type `Cstruct.t`

### ISSUE THREAD

**Issue by smolkaj** [frenetic-lang/ocaml-openflow#191]
Trying to build openflow, I get the following error:

> File "lib/OpenFlow0x01.ml", line 788, characters 18-23:
> Error: This expression has type Core.Std.bytes
>     but an expression was expected of type Cstruct.t
> Ideas?

**Comment by smolkaj** [comment]
I have OCaml version 4.02.3 installed, core version 112.35.01. Maybe you can help with this, @craig-riecke? Thanks!

**Comment by smolkaj** [comment]
Is this related to https://github.com/frenetic-lang/frenetic/issues/431? Do I need to pin an older version of core?

**Comment by craig-riecke** [comment]
Yup, this is Issue #425 and #431.  But you actually don't need ocaml-openflow repositiory anymore - all the code has been merged into frenetic/master.  Once you remove that, ther easiest way to pin core is just to do:

opam install -y frenetic

**Comment by smolkaj** [comment]
Ah, right.
I tried `opam install -y frenetic`, but the first thing it does is install openflow 0.9.1, which fails as above.
I also tried `checkout unified && make clean && make`. This fails with `Error: Unbound value Bytes.get`.
This is on MacOS, not the VM.

**Comment by craig-riecke** [comment]
Ah, the unified branch is defunct (it's all merged into master).  I oughta delete it.

I'm wondering if opam install -y frenetic is pulling the opam description of frenetic from your opam repo.  Try this from the root of your frenetic-vm (or subsitute src/frenetic for the root of your frenetic sandbox)

opam pin add frenetic src/frenetic -n -k git

**Comment by smolkaj** [comment]
@craig-riecke: Awesome, this works. Thanks!
